### ISSUE TITLE
Invalid L1i size: 96KB

### ISSUE THREAD

**Issue by gamerhat18** [Dr-Noob/cpufetch#64] opened 2021-04-08 09:04 UTC
```
❯ ./cpufetch --debug
[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.96 (x86_64 build)
AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G
- Max standard level: 0x0000000D
- Max extended level: 0x8000001E
- CPUID dump: 0x00660F01
```

**Comment by Dr-Noob** [comment] 2021-04-08 09:07
Duplicate of #39. 

Could you post the result of the commands I asked in my last messasge there? 

Thank, closing

**Closed by Dr-Noob** 2021-04-08 09:07 UTC
