### ISSUE TITLE
Extend supported OS/arch combinations

### ISSUE THREAD

**Issue by bmarwell** [Dr-Noob/cpufetch#142] opened 2022-05-07 17:27 UTC
Hey,

is there a list of combinations of platforms which are supported?

E.g. a table like this

Linux :: x64 :: ✅
Linux :: s390x :: ❌
AIX :: PPC64 :: ❓
Linux :: PPC64LE :: ❓
NetBSD :: aarch64 :: ✅

etc

**Comment by Dr-Noob** [comment] 2022-05-08 06:57
Do you mean [this](https://github.com/Dr-Noob/cpufetch#1-support) or do you mean a runtime option in cpufetch which shows that information?

**Comment by bmarwell** [comment] 2022-05-08 07:00
Yes, I changed the subject to "extend supported OS/arch" combinations. s390x is missing, for example. AIX as well.

**Comment by Dr-Noob** [comment] 2022-05-08 09:55
Ah yes, I read [your tweet](https://twitter.com/bmarwell/status/1522987443460481025). So yes, s390x and AIX support is missing. I'm open to discuss why cpufetch should or should not support them, and here's my point.

To provide the first port to a OS/arch, I need access to that platform (especially in the case of the arch). Because otherwise, I cannot be sure that the port will work on that platforms. Furthermore, to keep providing "good" support for these platforms, I should keep access to them. For example, in the case of PPC64, I had access to one of these and now I see bugs in the PPC64 backend, some of which are difficult to reproduce. It's sad for me to see that and not be able to fix them. Because if you can't reproduce the bug there's no way you can fix it properly.

I don't think there is a nearly easy way to have a free installation of AIX and I don't have any s390x around and I'm not willing to have one either. If you have a reasonable solution for that issues, I might be interested in adding support for them.

I'm closing the issue but feel free to continue the discussion if you wish.

**Closed by Dr-Noob** 2022-05-08 09:55 UTC

**Comment by bmarwell** [comment] 2022-05-08 11:39
@Dr-Noob 
You closed https://github.com/Dr-Noob/cpufetch/issues/142 with "I won't support these".
But my question was to add unsupported platforms to the overview list.

That's all.

**Comment by bmarwell** [comment] 2022-05-08 11:45
Linux on s390x and ppc64le:
https://github.com/marketplace/actions/run-on-architecture

I also added a feature request for GH Actions.

**Comment by Dr-Noob** [comment] 2022-05-08 13:54
Yes, I said that I won't support them because I have no way of setting up a suitable environment for working on it. I don't want Github actions. I prefer a non-cloud solution.

I don't think adding unsupported platforms to the overview list is a good idea. If there is an OS or architecture that does not appear in the list it's simply because it's not supported at the moment, there's no need to list each of them.
