### ISSUE TITLE
RISC-V support

### ISSUE THREAD

**Issue by Sakura286** [Dr-Noob/cpufetch#176] opened 2023-03-12 09:45 UTC
Hi,

I have read issue #101 and #133. I could provide ssh access to my [Hifive Unmatched](https://www.sifive.com/boards/hifive-unmatched) and help to access some other RISC-V boards. If you have interest in RISC-V porting, I can offer some help.

**Comment by Dr-Noob** [comment] 2023-03-12 11:13
I might jump in introducing RISC-V detection but first I'd like to see some results. I tried adding support multiple times in RISC-V in the past but the problem is that it seems so hard for user-level programs to detect CPU features.

For example, can you show me the output of `lscpu` and `cat /proc/cpuinfo`? Also, do you know of any program other than lscpu that shows CPU information in RISC-V? I need some sort of starting point to look at.

**Comment by Sakura286** [comment] 2023-03-12 17:05
```
$ lscpu 
Architecture:          riscv64
  Byte Order:          Little Endian
CPU(s):                4
  On-line CPU(s) list: 0-3
NUMA:                  
  NUMA node(s):        1
  NUMA node0 CPU(s):   0-3
```
```
$ cat /proc/cpuinfo 
processor	: 0
hart		: 1
isa		: rv64imafdc
mmu		: sv39
uarch		: sifive,bullet0

processor	: 1
hart		: 2
isa		: rv64imafdc
mmu		: sv39
uarch		: sifive,bullet0

processor	: 2
hart		: 3
isa		: rv64imafdc
mmu		: sv39
uarch		: sifive,bullet0

processor	: 3
hart		: 4
isa		: rv64imafdc
mmu		: sv39
uarch		: sifive,bullet0
```
```
$ inxi -C
CPU:
  Info: quad core model: N/A variant: bullet0 bits: 64 type: MCP cache: L2: 2 MiB
  Speed: N/A min/max: N/A cores: No per core speed data found.
```

I noticed that some info could be found at [.dtsi file](https://github.com/torvalds/linux/blob/master/arch/riscv/boot/dts/sifive/fu740-c000.dtsi). They can be gotten by this way:

```
$ cd /boot & ls
  extlinux	System.map-5.19.0-1-riscv64	config-5.19.0-1-riscv64  hifive-unmatched-a00.dtb	initrd.img-5.19.0-1-riscv64
  vmlinux-5.19.0-1-riscv64
$ dtc -I dtb hifive-unmatched-a00.dtb -O dts -o hifive-unmatched-a00.dts
$ cat hifive-unmatched-a00.dts
```

I have also tried `linuxinfo`, `hwinfo --cpu`, `lshw -C CPU`, but it seems that they can't provide more information.
```
$ linuxinfo
Linux unmatched 5.18.0-3-riscv64 #1 SMP Debian 5.18.14-1 (2022-07-23)
Four sifive,bullet0 processors, ? total bogomips, 15986M RAM
System library 2.36.0
```
```
$ hwinfo --cpu
01: None 00.0: 10103 CPU                                        
  [Created at cpu.710]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: RISC-V
  Vendor: "sifive,bullet0"
  Model: 0.0.0 "rv64imafdc"
  Config Status: cfg=new, avail=yes, need=no, active=unknown

02: None 00.0: 10103 CPU
  [Created at cpu.710]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: RISC-V
  Vendor: "sifive,bullet0"
  Model: 0.0.0 "rv64imafdc"
  Config Status: cfg=new, avail=yes, need=no, active=unknown

03: None 00.0: 10103 CPU
  [Created at cpu.710]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: RISC-V
  Vendor: "sifive,bullet0"
  Model: 0.0.0 "rv64imafdc"
  Config Status: cfg=new, avail=yes, need=no, active=unknown

04: None 00.0: 10103 CPU
  [Created at cpu.710]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: RISC-V
  Vendor: "sifive,bullet0"
  Model: 0.0.0 "rv64imafdc"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
```
```
$lshw -C CPU
  *-cpu:0                   
       description: CPU
       product: cpu
       physical id: 1
       bus info: cpu@0
       width: 32 bits
  *-cpu:1
       description: CPU
       product: cpu
       physical id: 2
       bus info: cpu@1
       width: 32 bits
  *-cpu:2
       description: CPU
       product: cpu
       physical id: 3
       bus info: cpu@2
       width: 32 bits
  *-cpu:3
       description: CPU
       product: cpu
       physical id: 4
       bus info: cpu@3
       width: 32 bits
  *-cpu:4 DISABLED
       description: CPU
       product: cpu
       physical id: 5
       bus info: cpu@4
```

**Comment by Dr-Noob** [comment] 2023-03-17 19:09
Thanks for the detailed information. 

I assume this is a SiFive Freedom U740 (FU740) SoC, right? To me, the dts is the most promising information source so far. Can you show the contents of that file? Or is it somewhat similar to what you referred to in the [dtsi link](https://github.com/torvalds/linux/blob/master/arch/riscv/boot/dts/sifive/fu740-c000.dtsi)? Reading that file we can easily find that it is a fu740 and many usefull specs.

**Comment by Sakura286** [comment] 2023-03-26 14:45
I'm so sorry for the delayed reply.

> Or is it somewhat similar to what you referred to in the [dtsi link](https://github.com/torvalds/linux/blob/master/arch/riscv/boot/dts/sifive/fu740-c000.dtsi)?

Yes, [fu740-c000.dtsi](https://github.com/torvalds/linux/blob/master/arch/riscv/boot/dts/sifive/fu740-c000.dtsi) is included in  [hifive-unmatched-a00.dts](https://github.com/torvalds/linux/blob/master/arch/riscv/boot/dts/sifive/hifive-unmatched-a00.dts), and hifive-unmatched-a00.dts is almost the same as [the one on my Unmatched](https://gist.github.com/Sakura286/dbfeee3c92aa92bfb8a047ed794544d7). It seems that nothing new could be found in the `.dts` file of the real mechine.

**Comment by exkc** [comment] 2023-03-27 14:50
@Dr-Noob  allwiner d1-h(it is a riscv soc) support  /sys/bus/nvmem/devices/sunxi-sid0/nvmem. (See #173)

**Comment by exkc** [comment] 2023-03-27 14:54
@Sakura286 can you run `cat /proc/device-tree/compatible` on your riscv sbc ? Thank

**Comment by Dr-Noob** [comment] 2023-03-27 15:49
> @Dr-Noob allwinner d1-h(it is a riscv soc) support /sys/bus/nvmem/devices/sunxi-sid0/nvmem. (See #173)

And does it have relevant files under /boot (e.g., a .dts or .dtb file)?

**Comment by exkc** [comment] 2023-03-28 05:31
https://github.com/torvalds/linux/blob/master/arch/riscv/boot/dts/allwinner/sun20i-d1-mangopi-mq-pro.dts
https://github.com/torvalds/linux/blob/master/arch/riscv/boot/dts/allwinner/sun20i-d1.dtsi

**Comment by exkc** [comment] 2023-03-28 14:23
@Sakura286 @Dr-Noob I think we can use this to identify the soc (it maybe not a good idea bc it is depended  on the device-tree)

**Comment by Dr-Noob** [comment] 2023-03-29 18:15
> Hi,
> 
> I have read issue #101 and #133. I could provide ssh access to my [Hifive Unmatched](https://www.sifive.com/boards/hifive-unmatched) and help to access some other RISC-V boards. If you have interest in RISC-V porting, I can offer some help.

Well, if you could give me access to one of your RISC-V boards it would be much easier for me to develop the port. If you are willing to do so, please mail me at peibolms @ gmail dot com :+1:

**Comment by Patola** [comment] 2023-03-31 01:47
Great so see this discussion, I've got the StarFive VisionFive 2 development board, here are my data:
```
[3:41] [root@riscola ~]# lscpu
Architecture:          riscv64
  Byte Order:          Little Endian
CPU(s):                4
  On-line CPU(s) list: 0-3
```
```
[3:41] [root@riscola ~]# cat /proc/cpuinfo 
processor	: 0
hart		: 1
isa		: rv64imafdc
mmu		: sv39
isa-ext		: 
uarch		: sifive,u74-mc

processor	: 1
hart		: 2
isa		: rv64imafdc
mmu		: sv39
isa-ext		: 
uarch		: sifive,u74-mc

processor	: 2
hart		: 3
isa		: rv64imafdc
mmu		: sv39
isa-ext		: 
uarch		: sifive,u74-mc

processor	: 3
hart		: 4
isa		: rv64imafdc
mmu		: sv39
isa-ext		: 
uarch		: sifive,u74-mc
```
```
[3:41] [root@riscola ~]# inxi -C
CPU:
  Info: single core model: N/A variant: u74-mc bits: 64 type: MT cache:
    L2: 2 MiB
  Speed (MHz): avg: 1500 min/max: 375/1500 cores: 1: 1500 2: 1500 3: 1500
    4: 1500
```
```
[3:42] [root@riscola ~]# cd /boot && ls
System.map-5.15.2-cwt10+  config-5.15.2-cwt10+  dtbs  extlinux  initrd.img-5.15.2-cwt10+  uEnv.txt  vmlinuz-5.15.2-cwt10+
```
However, I don't know which dtb to get the dts from:
```
[3:44] [root@riscola dtbs]# cd /boot/dtbs
[3:44] [root@riscola dtbs]# find . -type f
./5.15.2-cwt10+/sifive/hifive-unleashed-a00.dtb
./5.15.2-cwt10+/sifive/hifive-unmatched-a00.dtb
./5.15.2-cwt10+/starfive/evb-overlay/jh7110-evb-overlay-rgb2hdmi.dtbo
./5.15.2-cwt10+/starfive/evb-overlay/jh7110-evb-overlay-can.dtbo
./5.15.2-cwt10+/starfive/evb-overlay/jh7110-evb-overlay-uart4-emmc.dtbo
./5.15.2-cwt10+/starfive/evb-overlay/jh7110-evb-overlay-sdio.dtbo
./5.15.2-cwt10+/starfive/evb-overlay/jh7110-evb-overlay-spi.dtbo
./5.15.2-cwt10+/starfive/evb-overlay/jh7110-evb-overlay-uart5-pwm.dtbo
./5.15.2-cwt10+/starfive/vf2-overlay/vf2-overlay-uart3-i2c.dtbo
./5.15.2-cwt10+/starfive/jh7110-evb-uart5-pwm-i2c-tdm.dtb
./5.15.2-cwt10+/starfive/jh7110-evb-can-pdm-pwmdac.dtb
./5.15.2-cwt10+/starfive/jh7110-evb-dvp-rgb2hdmi.dtb
./5.15.2-cwt10+/starfive/jh7110-evb-i2s-ac108.dtb
./5.15.2-cwt10+/starfive/jh7110-evb-pcie-i2s-sd.dtb
./5.15.2-cwt10+/starfive/jh7110-evb-spi-uart2.dtb
./5.15.2-cwt10+/starfive/jh7110-evb-uart1-rgb2hdmi.dtb
./5.15.2-cwt10+/starfive/jh7110-evb-uart4-emmc-spdif.dtb
./5.15.2-cwt10+/starfive/jh7110-evb-usbdevice.dtb
./5.15.2-cwt10+/starfive/jh7110-evb.dtb
./5.15.2-cwt10+/starfive/jh7110-fpga.dtb
./5.15.2-cwt10+/starfive/jh7110-visionfive-v2-A10.dtb
./5.15.2-cwt10+/starfive/jh7110-visionfive-v2-A11.dtb
./5.15.2-cwt10+/starfive/jh7110-visionfive-v2-ac108.dtb
./5.15.2-cwt10+/starfive/jh7110-visionfive-v2-wm8960.dtb
./5.15.2-cwt10+/starfive/jh7110-visionfive-v2.dtb
./sifive/hifive-unleashed-a00.dtb
./sifive/hifive-unmatched-a00.dtb
./starfive/evb-overlay/jh7110-evb-overlay-can.dtbo
./starfive/evb-overlay/jh7110-evb-overlay-rgb2hdmi.dtbo
./starfive/evb-overlay/jh7110-evb-overlay-sdio.dtbo
./starfive/evb-overlay/jh7110-evb-overlay-spi.dtbo
./starfive/evb-overlay/jh7110-evb-overlay-uart4-emmc.dtbo
./starfive/evb-overlay/jh7110-evb-overlay-uart5-pwm.dtbo
./starfive/vf2-overlay/vf2-overlay-uart3-i2c.dtbo
./starfive/jh7110-evb-can-pdm-pwmdac.dtb
./starfive/jh7110-evb-dvp-rgb2hdmi.dtb
./starfive/jh7110-evb-i2s-ac108.dtb
./starfive/jh7110-evb-pcie-i2s-sd.dtb
./starfive/jh7110-evb-spi-uart2.dtb
./starfive/jh7110-evb-uart1-rgb2hdmi.dtb
./starfive/jh7110-evb-uart4-emmc-spdif.dtb
./starfive/jh7110-evb-uart5-pwm-i2c-tdm.dtb
./starfive/jh7110-evb-usbdevice.dtb
./starfive/jh7110-evb.dtb
./starfive/jh7110-fpga.dtb
./starfive/jh7110-visionfive-v2-A10.dtb
./starfive/jh7110-visionfive-v2-A11.dtb
./starfive/jh7110-visionfive-v2-ac108.dtb
./starfive/jh7110-visionfive-v2-wm8960.dtb
./starfive/jh7110-visionfive-v2.dtb
```
```
[3:46] [root@riscola dtbs]# hwinfo --cpu              
01: None 00.0: 10103 CPU                                        
  [Created at cpu.707]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: RISC-V
  Vendor: "sifive,u74-mc"
  Model: 0.0.0 "rv64imafdc"
  Config Status: cfg=new, avail=yes, need=no, active=unknown

02: None 00.0: 10103 CPU
  [Created at cpu.707]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: RISC-V
  Vendor: "sifive,u74-mc"
  Model: 0.0.0 "rv64imafdc"
  Config Status: cfg=new, avail=yes, need=no, active=unknown

03: None 00.0: 10103 CPU
  [Created at cpu.707]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: RISC-V
  Vendor: "sifive,u74-mc"
  Model: 0.0.0 "rv64imafdc"
  Config Status: cfg=new, avail=yes, need=no, active=unknown

04: None 00.0: 10103 CPU
  [Created at cpu.707]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: RISC-V
  Vendor: "sifive,u74-mc"
  Model: 0.0.0 "rv64imafdc"
  Config Status: cfg=new, avail=yes, need=no, active=unknown
```
```
[3:46] [root@riscola dtbs]# lshw -C cpu
  *-cpu:0                   
       description: CPU
       product: cpu
       physical id: 1
       bus info: cpu@0
       size: 1500MHz
       capacity: 1500MHz
       width: 32 bits
       capabilities: cpufreq
  *-cpu:1
       description: CPU
       product: cpu
       physical id: 2
       bus info: cpu@1
       size: 1500MHz
       capacity: 1500MHz
       width: 32 bits
       capabilities: cpufreq
  *-cpu:2
       description: CPU
       product: cpu
       physical id: 3
       bus info: cpu@2
       size: 1500MHz
       capacity: 1500MHz
       width: 32 bits
       capabilities: cpufreq
  *-cpu:3
       description: CPU
       product: cpu
       physical id: 4
       bus info: cpu@3
       size: 1500MHz
       capacity: 1500MHz
       width: 32 bits
       capabilities: cpufreq
  *-cpu:4 DISABLED
       description: CPU
       product: cpu
       physical id: 5
       bus info: cpu@4
```

**Comment by exkc** [comment] 2023-03-31 08:32
@Patola 
> However, I don't know which dtb to get the dts from:

cat /proc/device-tree/compatible

**Comment by Patola** [comment] 2023-03-31 08:45
> @Patola
> 
> > However, I don't know which dtb to get the dts from:
> 
> You just need to run this command cat /proc/device-tree/compatible

```
[10:44] [root@riscola ~]# cat /proc/device-tree/compatible                                           
starfive,visionfive-v2starfive,jh7110#                                                                                                                                                                                               [10:44] [root@riscola ~]# cd /boot/dtbs/starfive                                                     
[10:44] [root@riscola starfive]# dtc -I dtb jh7110-visionfive-v2.dtb -O dts -o /tmp/jh7110-visionfive-v2.dts
/tmp/jh7110-visionfive-v2.dts: Warning (unit_address_vs_reg): /soc/clock-controller: node has a reg or ranges property, but no unit name
/tmp/jh7110-visionfive-v2.dts: Warning (unit_address_vs_reg): /soc/usbdrd: node has a reg or ranges property, but no unit name
(... lots of warnings ...)
```

**Comment by exkc** [comment] 2023-03-31 09:14
> I'll create a new branch with some new code to add support for RISC-V soon. In the meantime, @exkc can you also paste the output of cat /proc/device-tree/compatible?

yes ,but it is not needed , right? since it support /sys/bus/nvmem/devices/sunxi-sid0/nvmem.

![image](https://user-images.githubusercontent.com/70055899/229078521-1d288f60-822e-479c-ba54-667fc8e47f2d.png)

**Comment by exkc** [comment] 2023-03-31 10:14
wait we cant identifty d1s n d1h bc they seem to compatible as allwinner,sun20i-d1

**Comment by Dr-Noob** [comment] 2023-04-01 16:54
I'm in the middle of the porting process - I am going to start with the HiFive Unmatched shown by @Sakura286. So I was looking that `/proc/cpuinfo`, as well as `lscpu` both report that this SoC has 4 cores. However, [hifive says](https://www.sifive.com/boards/hifive-unmatched):

"_The development board is powered by the SiFive Freedom U740 (FU740), an SoC that includes a high-performance multi-core, 64-bit dual-issue, superscalar RISC-V processor (SiFive Essential U74-MC) with .... A 5th core (a SiFIve Essential S71 monitor core) is available for real time applications_"

So this SoC has 4+1 cores, 5 in total, whereas Linux apparently is only aware of 4 of them (the first 4)? Any ideas @Patola @Sakura286 @exkc?

**Comment by Dr-Noob** [comment] 2023-04-01 16:56
> > I'll create a new branch with some new code to add support for RISC-V soon. In the meantime, @exkc can you also paste the output of cat /proc/device-tree/compatible?
> 
> yes ,but it is not needed , right? since it support /sys/bus/nvmem/devices/sunxi-sid0/nvmem.
> 
> ![image](https://user-images.githubusercontent.com/70055899/229078521-1d288f60-822e-479c-ba54-667fc8e47f2d.png)

Sure, we can use `nvmem`, but it is always desirable to use a general method (like the device tree) to detect as many systems as possible, and only rely in alternative methods when the general one does not work.

**Comment by Patola** [comment] 2023-04-01 17:34
> So this SoC has 4+1 cores, 5 in total, whereas Linux apparently is only aware of 4 of them (the first 4)? Any ideas @Patola @Sakura286 @exkc?

Absolutely no idea, and that left me very curious. I did not even know such "invisible" cores exist. BTW, maybe this discussion on fields of RISC-V to get for the linuxinfo utility can help? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012077

**Comment by exkc** [comment] 2023-04-02 03:36
> So this SoC has 4+1 cores, 5 in total, whereas Linux apparently is only aware of 4 of them (the first 4)? Any ideas @Patola @Sakura286 @exkc?

 we might able to enable in the drvice tree i think


./starfive/evb-overlay/jh7110-evb-overlay-can.dtbo
 i want to take a look of that

**Comment by exkc** [comment] 2023-04-02 03:40
OH we can

![image](https://user-images.githubusercontent.com/70055899/229329930-9e2ee517-ff65-4de6-b636-881ceceb9f27.png)


Found in the device tree that you have sented out.

**Comment by Sakura286** [comment] 2023-04-02 04:06
> "The development board is powered by the SiFive Freedom U740 (FU740), an SoC that includes a high-performance multi-core, 64-bit dual-issue, superscalar RISC-V processor (SiFive Essential U74-MC) with .... A 5th core (a SiFIve Essential S71 monitor core) is available for real time applications"

Floating extensions (F & D) are not  implemented in S71 to satisfied Linux required(rv64gc, that means rv64imafdc). So cpu0 is disabled in dtsi file. It seems that S71 is for metal programming till now.

https://www.cnx-software.com/2018/11/02/sifive-7-series-risc-v-cores-e76-s76-u74/
https://forums.sifive.com/t/how-about-the-s7-core/5028

**Comment by Dr-Noob** [comment] 2023-04-07 08:40
> > "The development board is powered by the SiFive Freedom U740 (FU740), an SoC that includes a high-performance multi-core, 64-bit dual-issue, superscalar RISC-V processor (SiFive Essential U74-MC) with .... A 5th core (a SiFIve Essential S71 monitor core) is available for real time applications"
> 
> Floating extensions (F & D) are not implemented in S71 to satisfy Linux required(rv64gc, that means rv64imafdc). So cpu0 is disabled in dtsi file. It seems that S71 is for bare metal programming till now.
> 
> https://www.cnx-software.com/2018/11/02/sifive-7-series-risc-v-cores-e76-s76-u74/ https://forums.sifive.com/t/how-about-the-s7-core/5028

That seems a very plausible explanation. cpufetch will report only the "active" cores tough, so in this case it will only show all except the S71.

**Comment by Dr-Noob** [comment] 2023-04-07 08:42
Ok, so I have implemented the preliminary support for RISC-V in `riscv` branch. Can you guys @Patola @Sakura286 @exkc give it a try? Remember to checkout to `riscv` branch before compiling (e.g., `git checkout riscv`).

PS: @Sakura286 I lost access to the RISC-V machine - I committed a few patches in my non RISC-V machine so it wouldn't surprise me if there is some errors.

**Comment by exkc** [comment] 2023-04-07 08:53
@Dr-Noob https://wiki.postmarketos.org/wiki/QEMU_riscv64_(qemu-riscv64)

https://wiki.postmarketos.org/wiki/Category:QEMU


you can make a pm os riscv via pm bootstrap btw

**Comment by Patola** [comment] 2023-04-07 08:54
```
[10:53] [169] [patola@riscola cpufetch]% make
cc -Wall -Wextra -pedantic -DARCH_RISCV -Wno-unused-parameter -std=c99 -fstack-protector-all -O2 -Wfloat-equal -Wshadow -Wpointer-arith -DGIT_FULL_VERSION=\""v1.03-31-g0ef0"\" src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/riscv/riscv.c src/riscv/uarch.c src/riscv/soc.c src/riscv/udev.c -o cpufetch
src/common/printer.c: In function ‘print_cpufetch_riscv’:
src/common/printer.c:937:9: warning: unused variable ‘features’ [-Wunused-variable]
  937 |   char* features = get_str_features(cpu);
      |         ^~~~~~~~
[10:54] [170] [patola@riscola cpufetch]% ls -latr
total 116
drwxr-xr-x 1 patola patola    16 Apr  7 10:53 ..
drwxr-xr-x 1 patola patola    18 Apr  7 10:53 .github
-rw-r--r-- 1 patola patola  2985 Apr  7 10:53 CONTRIBUTING.md
-rw-r--r-- 1 patola patola    13 Apr  7 10:53 .gitignore
-rw-r--r-- 1 patola patola 18092 Apr  7 10:53 LICENSE
-rw-r--r-- 1 patola patola  6213 Apr  7 10:53 README.md
-rw-r--r-- 1 patola patola  3448 Apr  7 10:53 cpufetch.1
drwxr-xr-x 1 patola patola   138 Apr  7 10:53 doc
drwxr-xr-x 1 patola patola   214 Apr  7 10:53 pictures
-rw-r--r-- 1 patola patola  4620 Apr  7 10:53 Makefile
drwxr-xr-x 1 patola patola    40 Apr  7 10:53 src
drwxr-xr-x 1 patola patola   138 Apr  7 10:53 .git
drwxr-xr-x 1 patola patola   184 Apr  7 10:53 .
-rwxr-xr-x 1 patola patola 68152 Apr  7 10:53 cpufetch
[10:54] [171] [patola@riscola cpufetch]% ./cpufetch

                                                               
                                ************                   
                    %%%%%%%%%    ***********                   
                    %%%%%%%%%%   **********                    
                    %%%%%%%%%    *********                     
                    %           ********                       
                    %%      .*********     %                   SoC:                 Unknown
                    %%%%     *******     %%%                   Technology:          Unknown
                    %%%%%%.    ****    %%%%%                   Microarchitecture:   Unknown
                    %%%%%%%%.        %%%%%%%                   Cores:               4 cores
                                                               Max Frequency:       1.500 GHz
                                                               Peak Performance:    6.00 GFLOP/s
 ###########   ##   .#########    #########   .##           ## 
 ##        ##  ##  ##           ##              ###       ###  
 ###########   ##  ##########. ##          ####  .##     ##    
 ##     ###    ##           ##. ##                 ### ###     
 ##       ###  ##  ##########.   ##########          ###       
                                                               

[10:54] [172] [patola@riscola cpufetch]% 
```

**Comment by Dr-Noob** [comment] 2023-04-07 09:19
I forgot to say that when running the program please add the `-v` flag (e.g., run `./cpufetch -v`). Can you check again with `-v` @Patola?

**Comment by Dr-Noob** [comment] 2023-04-07 09:22
As you will see, there is no information available under `Microarchitecture`. I don't know if there is a way to get the core type (for example, in the case of the SiFife unmatched it would be SiFive Essential U74-MC) but if you guys have any idea please just let me know.

**Comment by Patola** [comment] 2023-04-07 09:56
Exact same screen
```
[11:54] [172] [patola@riscola cpufetch]% ./cpufetch -v
[WARNING]: SoC detection failed using device tree

                                                               
                                ************                   
                    %%%%%%%%%    ***********                   
                    %%%%%%%%%%   **********                    
                    %%%%%%%%%    *********                     
                    %           ********                       
                    %%      .*********     %                   SoC:                 Unknown
                    %%%%     *******     %%%                   Technology:          Unknown
                    %%%%%%.    ****    %%%%%                   Microarchitecture:   Unknown
                    %%%%%%%%.        %%%%%%%                   Cores:               4 cores
                                                               Max Frequency:       1.500 GHz
                                                               Peak Performance:    6.00 GFLOP/s
 ###########   ##   .#########    #########   .##           ## 
 ##        ##  ##  ##           ##              ###       ###  
 ###########   ##  ##########. ##          ####  .##     ##    
 ##     ###    ##           ##. ##                 ### ###     
 ##       ###  ##  ##########.   ##########          ###       
                                                               
[11:54] [173] [patola@riscola cpufetch]% 
```

@Dr-Noob the bug report for the linuxinfo utility with a long discussion on how to get the fields did not help on that?

**Comment by Dr-Noob** [comment] 2023-04-07 14:20
> Exact same screen
> 
> ```
> [11:54] [172] [patola@riscola cpufetch]% ./cpufetch -v
> [WARNING]: SoC detection failed using device tree
> 
>                                                                
>                                 ************                   
>                     %%%%%%%%%    ***********                   
>                     %%%%%%%%%%   **********                    
>                     %%%%%%%%%    *********                     
>                     %           ********                       
>                     %%      .*********     %                   SoC:                 Unknown
>                     %%%%     *******     %%%                   Technology:          Unknown
>                     %%%%%%.    ****    %%%%%                   Microarchitecture:   Unknown
>                     %%%%%%%%.        %%%%%%%                   Cores:               4 cores
>                                                                Max Frequency:       1.500 GHz
>                                                                Peak Performance:    6.00 GFLOP/s
>  ###########   ##   .#########    #########   .##           ## 
>  ##        ##  ##  ##           ##              ###       ###  
>  ###########   ##  ##########. ##          ####  .##     ##    
>  ##     ###    ##           ##. ##                 ### ###     
>  ##       ###  ##  ##########.   ##########          ###       
>                                                                
> [11:54] [173] [patola@riscola cpufetch]% 
> ```
> 
> @Dr-Noob the bug report for the linuxinfo utility with a long discussion on how to get the fields did not help on that?

In [this comment](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012077#45) they say the only way to do this is to search for the `uarch` or `model name` field in `/proc/cpuinfo`. I have added a new commit so parse `uarch` field. I thinks it's not an elegant way but I guess we don't have better options. Also, I have updated the project with a new commit to fix your SoC error. 

If you try again, it should show the right SoC, Technology, Microarchitecture and manufacturer logo.

**Comment by Patola** [comment] 2023-04-07 14:36
Indeed. Thanks!
```
[16:35] [182] [patola@riscola cpufetch]% ./cpufetch -v

                          #######                 
                     ################.            
                ############   ###########        
            ############           ##########.    
       ############           #         ######    
    ###########               #####         ##    
   #######.                   ##########          
  ######            ###         *###########      
  ######            #######.         ##########   
   #########        ############         ######   SoC:                 StarFive VisionFive 2
     ###########.        ###########*         #   Technology:          28nm
         ############        ############         Microarchitecture:   U74-MC
   #         ############.       .###########     Cores:               4 cores
   ######         ###########         #########   Max Frequency:       1.500 GHz
   ##########         .######,            #####   Peak Performance:    6.00 GFLOP/s
      ############         ##.            #####.  
           #########                   ########   
    ##         #####               ##########.    
    #######        #          ############        
    ###########           ###########.            
        ###########. ############                 
            ################                      
                 #######                          
            ###########################       [3
```

**Comment by Dr-Noob** [comment] 2023-04-08 11:03
> Indeed. Thanks!
> 
> ```
> [16:35] [182] [patola@riscola cpufetch]% ./cpufetch -v
> 
>                           #######                 
>                      ################.            
>                 ############   ###########        
>             ############           ##########.    
>        ############           #         ######    
>     ###########               #####         ##    
>    #######.                   ##########          
>   ######            ###         *###########      
>   ######            #######.         ##########   
>    #########        ############         ######   SoC:                 StarFive VisionFive 2
>      ###########.        ###########*         #   Technology:          28nm
>          ############        ############         Microarchitecture:   U74-MC
>    #         ############.       .###########     Cores:               4 cores
>    ######         ###########         #########   Max Frequency:       1.500 GHz
>    ##########         .######,            #####   Peak Performance:    6.00 GFLOP/s
>       ############         ##.            #####.  
>            #########                   ########   
>     ##         #####               ##########.    
>     #######        #          ############        
>     ###########           ###########.            
>         ###########. ############                 
>             ################                      
>                  #######                          
>             ###########################       [3
> ```

There you go! Looks like the ascii logo was a bit bugged - I have fixed it in a recent commit. I'll work in the RISC-V extension next.

In the meantime, I'll wait for the results of @Sakura286 and @exkc. Also, I'm curious to know the peak performance of RISC-V chips. For the VisionFive 2 cpufetch shows 6 GFLOP/s because of 4 (cores) * 1.5 (Freq). However, this might change if the CPU supports vector instructions or FMA. I assume this will be the case of CPUs with the `V` extension? Might be worth some source confirming this or going into more detail, but I've been searching and found nothing so far.

**Comment by exkc** [comment] 2023-04-08 14:34
![2023-04-08_22-33](https://user-images.githubusercontent.com/70055899/230726926-e7f2cd64-7d0f-4239-83bf-732d9c5b0137.png)

**Comment by exkc** [comment] 2023-04-08 14:38
![Uploading 2023-04-08_22-37.png…]()

**Comment by exkc** [comment] 2023-04-08 14:38
![2023-04-08_22-37](https://user-images.githubusercontent.com/70055899/230727126-544ce445-0556-4efa-aa44-964ec1fe4b36.png)

**Comment by exkc** [comment] 2023-04-08 14:43
![2023-04-08_22-39](https://user-images.githubusercontent.com/70055899/230727380-ba490038-dfd0-4f5d-be93-f3c52accf88b.png)
btw i use this kernel https://github.com/smaeul/linux/tree/riscv/d1-wip

**Comment by Sakura286** [comment] 2023-04-09 06:02
![2023-04-09 13 59 21](https://user-images.githubusercontent.com/22614226/230757150-5717e2ec-437f-4325-b688-76db7cb45b10.png)

> PS: @Sakura286 I lost access to the RISC-V machine - I committed a few patches in my non RISC-V machine so it wouldn't surprise me if there is some errors.

Fpr service was down. The machine is now online.

**Comment by Dr-Noob** [comment] 2023-04-13 15:56
I have implemented the extensions detection and merged the `riscv` branch into the master branch. I think we can go into a last round of checking that everything works. Can you guys @Patola @Sakura286 @exkc run the last version? Everything should be working.

Also, if any has suggestions, feel free to ask. Otherwise, if everything works, I'll close the issue and assume the RISC-V port was completed successfully.

**Comment by Patola** [comment] 2023-04-13 16:34
used the `cpufetch-git` PKGBUILD, compiled into an arch package and installed (`makepkg -si`):
```
[18:33] [235] [patola@riscola cpufetch-git]% cpufetch 

                          #######                 
                     ################.            
                ############   ###########        
            ############           ##########.    
       ############           #         ######    SoC:                 StarFive VisionFive 2
    ###########               #####         ##    Technology:          28nm
   #######.                   ##########          Microarchitecture:   U74
  ######            ###         *###########      Cores:               4 cores
  ######            #######.         ##########   Max Frequency:       1.500 GHz
   #########        ############         ######   Extensions:          rv64imafdc
     ###########.        ###########*         #    - (I) Integer Instruction Set
         ############        ############          - (M) Integer Multiplication and Division
   #         ############.       .###########      - (A) Atomic Instructions
   ######         ###########         #########    - (F) Single-Precision Floating-Point
   ##########         .######,            #####    - (D) Double-Precision Floating-Point
      ############         ##.            #####.   - (C) Compressed Instructions
           #########                   ########   Peak Performance:    6.00 GFLOP/s
    ##         #####               ##########.    
    #######        #          ############        
    ###########           ###########.            
        ###########. ############                 
            ################                      

```

**Comment by Sakura286** [comment] 2023-04-16 09:36
It is cool to see extension explanations!

![2023-04-16 17 33 42](https://user-images.githubusercontent.com/22614226/232290015-716d7c5f-1aa5-43a9-b2ad-9d5ca14be4cb.png)

**Comment by exkc** [comment] 2023-04-21 12:02
![2023-04-21_20-01](https://user-images.githubusercontent.com/70055899/233630629-ebb55cc6-36bd-4a64-b38c-b8a579552993.png)
:)

**Comment by Dr-Noob** [comment] 2023-04-22 11:01
Looking good! 

I think we can close this issue and consider the RISC-V support topic finished. If you have further issues or suggestions, feel free to open a new issue. 

And thank you all for your help!

**Closed by Dr-Noob** 2023-04-22 11:01 UTC
Labels: enhancement, help wanted
