### ISSUE TITLE
Coffee Lake U misdetected as Kaby Lake

### ISSUE THREAD

**Issue by philipl** [Dr-Noob/cpufetch#149] opened 2022-07-19 10:36 UTC
Coffee Lake U chips are classified as Kaby Lake in the code. There is a comment saying this came from wikichip, but wiki chip shows it as coffee lake.

https://en.wikichip.org/wiki/intel/microarchitectures/coffee_lake#CPUID

**Comment by Dr-Noob** [comment] 2022-09-05 08:21
Good catch! Should be fixed in 71a9308bed63a64b9e80bc115a0390cac2f8364f.

**Comment by Dr-Noob** [comment] 2023-01-06 14:42
So after some time I realized that this isn't as clear as it seems. 

I initially classified it as Kaby Lake because [wikichip says so](https://en.wikichip.org/wiki/intel/cores/kaby_lake_r):

| Core | ExtendedFamily | Family | ExtendedModel | Model | Stepping |
|:-----------:|:------------------:|:------------------:|:------------------:|:------------------:|:------------------:|
| U | 0 | 0x6 | 0x8 | 0xE | 0xA |

but it's true that [wikichip also says that this CPUID may also correspond to Coffee Lake U](https://en.wikichip.org/wiki/intel/microarchitectures/coffee_lake#CPUID). Then, how can we differentiate between them?

**Comment by philipl** [comment] 2023-01-06 17:27
How strange. Ideally, we'd find someone with a kaby lake chip to check what the actual value is. Would Intel really have shipped them with the same identifier?

**Comment by Dr-Noob** [comment] 2023-01-28 07:37
I noticed this issue because my laptop is a Kaby Lake CPU and it is now being miss detected as Coffee Lake. So I can confirm that the actual stepping value for Kaby Lake is 10, not 9 - so Wikipedia is wrong and wikichip is right.

Maybe there is another way to differentiate even if they have the same CPUID.

**Comment by Dr-Noob** [comment] 2023-01-28 07:49
[Wikichip page](https://en.wikichip.org/wiki/intel/cores/kaby_lake_r) says:

"_Kaby Lake R ... serving as a refresh to Kaby Lake U_"

"_**Although those microprocessors are still based on Kaby Lake, Intel has branded them as 8th Generation Core**_"

So there are only certain Kaby Lake chips (more specifically, Kaby Lake R) that are a "refresh" of Kaby Lake and that Intel marketed them as 8th Gen* but technically they are still Kaby Lake - that's why CPUID is reporting them as 8th Gen rather than 7th Gen.

Sadly, this is actually the second time I see [two different chips reporting the same CPUID](https://github.com/Dr-Noob/cpufetch/issues/122).

\* Kaby Lake are 7th Gen. (e.g., i5-7***) while my Kaby Lake CPU is marketed as 8th Gen (it is i5-8250U).

**Comment by Dr-Noob** [comment] 2023-01-28 08:08
I'd say that the last commit should fix this ambiguity - now my i5-8250U is being reported as Kaby Lake again. Can you check if it also works on your end?

**Comment by philipl** [comment] 2023-01-29 02:24
Thanks. I will check next week when I have access to the machine again.

**Comment by philipl** [comment] 2023-02-09 18:00
Works correctly. My machine is an i5-8259U and is being reported as Coffee Lake.

**Comment by Dr-Noob** [comment] 2023-02-10 21:26
That is some good news. Also, I did some search, and [wikichip](https://en.wikichip.org/wiki/intel/cpuid) clearly shows that this is not the only case in which a CPUID identification is shared by two different microarchitectures. But I'll take care of that in another issue - this one is solved now.

Thanks for the help!

**Closed by Dr-Noob** 2023-02-10 21:26 UTC
Labels: bug, help wanted
