### ISSUE TITLE
Does not build on MacOS

### ISSUE THREAD

**Issue by slinkouswasalreadytaken** [Dr-Noob/cpufetch#38] opened 2021-01-04 17:05 UTC
When installing through the git repository, I am unable to `make` the package. 

![Screen Shot 2021-01-04 at 12 04 33 PM](https://user-images.githubusercontent.com/53449377/103559961-02d40b80-4e85-11eb-82ca-33595fd05670.png)

![Screen Shot 2021-01-04 at 12 04 51 PM](https://user-images.githubusercontent.com/53449377/103559997-0d8ea080-4e85-11eb-8ff8-eefcbe815b92.png)

**Comment by Dr-Noob** [comment] 2021-01-05 21:33
Thank you for your feedback.

I have never tried to run cpufetch on MacOS, so it does not surprise me that it does not even build. After all, I didn't notice any interest from MacOS users. Now that the project has grown enough, I am more interested in supporting it.
I have pushed a new commit in the bugfix branch that should solve the issue. Unfortunately, I'm not sure if I will leave the implementation as it is in this commit or not. I would like to confirm if it builds and works properly on macOS with this fix, but the implementation under the hood is pretty awful. macOS does not allow to pin a thread to a specific CPU core, and that is a big pain in the as...

Just test the new fix and let me know how it goes. You will notice that cpufetch runs for several seconds until you get the output. This is the expected behaviour, and it is the downside of the only hacky way I found to overcome the macOS limitation I just mentioned.

**Comment by slinkouswasalreadytaken** [comment] 2021-01-06 17:08
Unfortunately this doesn't seem to do the trick, I am getting practically the same result

```
~/cpufetch(master) » make install                                                                                                                      2 ↵ slinkous@MacBook-Air
gcc -Wall -Wextra -Werror -pedantic -fstack-protector-all -pedantic -std=c99 -DARCH_X86 -Wfloat-equal -Wshadow -Wpointer-arith src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/x86/cpuid.c src/x86/apic.c src/x86/cpuid_asm.c src/x86/uarch.c -o cpufetch
src/x86/apic.c:75:5: error: use of undeclared identifier 'cpu_set_t'
    cpu_set_t currentCPU;
    ^
src/x86/apic.c:76:5: error: implicit declaration of function 'CPU_ZERO' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    CPU_ZERO(&currentCPU);
    ^
src/x86/apic.c:76:15: error: use of undeclared identifier 'currentCPU'
    CPU_ZERO(&currentCPU);
              ^
src/x86/apic.c:77:5: error: implicit declaration of function 'CPU_SET' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    CPU_SET(cpu_id, &currentCPU);
    ^
src/x86/apic.c:77:22: error: use of undeclared identifier 'currentCPU'
    CPU_SET(cpu_id, &currentCPU);
                     ^
src/x86/apic.c:78:9: error: implicit declaration of function 'sched_setaffinity' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (sched_setaffinity (0, sizeof(currentCPU), &currentCPU) == -1) {
        ^
src/x86/apic.c:78:38: error: use of undeclared identifier 'currentCPU'
    if (sched_setaffinity (0, sizeof(currentCPU), &currentCPU) == -1) {
                                     ^
src/x86/apic.c:78:52: error: use of undeclared identifier 'currentCPU'
    if (sched_setaffinity (0, sizeof(currentCPU), &currentCPU) == -1) {
                                                   ^
8 errors generated.
make: *** [cpufetch] Error 1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/cpufetch(master) »
```

sudo does not help, and neither does omitting install.

**Comment by Dr-Noob** [comment] 2021-01-06 18:12
I pushed the commit to the **bugfix branch**, you need to checkout to the branch to try the new commit:

```
[noob@drnoob cpufetch]$ git checkout bugfix 
Switched to branch 'bugfix'
[noob@drnoob cpufetch]$ make
```

**Comment by slinkouswasalreadytaken** [comment] 2021-01-08 19:56
Hmm, this is odd

```
~/cpufetch(bugfix) » make                                                                                                                                  slinkous@MacBook-Air
gcc -Wall -Wextra -Werror -pedantic -fstack-protector-all -pedantic -std=c99 -DARCH_X86 -Wfloat-equal -Wshadow -Wpointer-arith src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/x86/cpuid.c src/x86/apic.c src/x86/cpuid_asm.c src/x86/uarch.c -o cpufetch
```

but whenever I type cpufetch, I get a command not found.

**Comment by Dr-Noob** [comment] 2021-01-08 20:15
`make` by default builds the source code, but does not install it, so the executable is just in the folder where you built it (not installed system wide), so you need to execute it specifying its path:

```
./cpufetch
```

**Comment by slinkouswasalreadytaken** [comment] 2021-01-08 21:23
It (mostly) lives!!!

```
~/cpufetch(bugfix) » ./cpufetch                                                                                                                            slinkous@MacBook-Air
open: No such file or directory
[ERROR]: Could not open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq'
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch is computing APIC IDs, please wait...



                                                              Name:              Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
                                                              Microarchitecture: Broadwell
                                                              Technology:        14nm
                                                              Max Frequency:     Unknown
                                                              Cores:             2 cores (4 threads)
                                                              AVX:               AVX,AVX2
                                                              FMA:               FMA3
                                                              L1i Size:          32KB (64KB Total)
                                                              L1d Size:          32KB (64KB Total)
                                                              L2 Size:           256KB (512KB Total)
                                                              L3 Size:           4MB
                                                              Peak Performance:  Unknown





--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/cpufetch(bugfix) »
```
The logo is there, it just does not copy


```
~/cpufetch(bugfix) » ./cpufetch --debug                                                                                                                    slinkous@MacBook-Air
open: No such file or directory
[ERROR]: Could not open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq'
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch is computing APIC IDs, please wait...cpufetch v0.94 (x86_64 build)
Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
- Max standard level: 0x00000014
- Max extended level: 0x80000008
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/cpufetch(bugfix) »
```

**Comment by Dr-Noob** [comment] 2021-01-08 22:51
Alright, that looks better. It is not surprising that `/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq` does not exist, though. I need more information in order to understand how can I proceed to fix this. Would you mind to run the following and paste the output here? 

```
sysctl hw.model
sysctl hw.cpufrequency
sysctl hw.cpufrequency_max
sysctl hw.cpufrequency_min
```

Let's see if it works...

**Comment by slinkouswasalreadytaken** [comment] 2021-01-09 15:45
Sure thing: 
```
hw.model: MacBookAir7,2
hw.cpufrequency: 2200000000
hw.cpufrequency_max: 2200000000
hw.cpufrequency_min: 2200000000
```

**Comment by Dr-Noob** [comment] 2021-01-10 08:12
Great! So you ask macOS which is the max frequency of your CPU and it tells you the base frequency (in your case, max frequency should be 3.1 GHz). I had a look over the internet and it seems like this is normal behavior. If macOS can't tell the max frequency, then I can't do anything about that.

I pushed a new commit to the `bugfix` branch (remember to run `git pull` to download the new commit). I just replaced the bug message with an error one. Since cpufetch is unable to fetch frequency, the expected behavior is to alert the user.

If this the behavior that you get, and you are happy with that, feel free to close the issue. I will merge the changes to the master branch after that.

**Comment by slinkouswasalreadytaken** [comment] 2021-01-12 17:12
Hmm, well it's different, but not necessarily any better.


```
~/cpufetch(bugfix*) » ./cpufetch                                                                                                                           slinkous@MacBook-Air
[ERROR]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x00000014)
cpufetch is computing APIC IDs, please wait...
```

Everything else works the same.

**Comment by Dr-Noob** [comment] 2021-01-14 17:38
This is the expected behavior. To obtain CPU frequency, there are two ways to do so:

- Ask the CPU itself
- Ask the OS

In your case, the CPU is too old and it is not possible to get the max frequency directly (this is why cpufetch says `Can't read frequency information from cpuid (needed level is 0x00000016, max is ...)`).
macOS does not seem to report the max frequency (it can report the base frequency, though), so cpufetch can't show your max frequency and shows you an error message to let you know that. 

This issue happens in Windows too, because it is neither capable of reporting the max frequency (maybe there is a way, but I don't know it). However, Linux is capable of telling you the max frequency in this case, so if you would run cpufetch on Linux, you would the all the fields completed (I understand you are not really interested in installing Linux on a mac, just explaining what's going on). Finally, peak performance is unknown because you need to know your max frequency to compute this value. 

You opened the issue because you could not build cpufetch on macOS. This issue has been solved, so I'm closing the issue and I will be merging the changes to the master branch soon. Thank you for your feedback, and feel free to open a new issue if you wish to report a new bug or a feature request for cpufetch.

**Closed by Dr-Noob** 2021-01-14 17:38 UTC

**Comment by Elgarni** [comment] 2021-04-09 14:14
@Dr-Noob I can't have it compile on my Mac machine:

```zsh
➜  cpufetch git:(master) make
gcc -Wall -Wextra -Werror -pedantic -fstack-protector-all -pedantic -std=c99 -DARCH_X86 -Wfloat-equal -Wshadow -Wpointer-arith src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/x86/cpuid.c src/x86/apic.c src/x86/cpuid_asm.c src/x86/uarch.c -o cpufetch
src/common/args.c:195:2: error: embedding a directive within macro arguments has undefined behavior
      [-Werror,-Wembedded-directive]
#else
 ^
1 error generated.
make: *** [cpufetch] Error 1
```
