### ISSUE TITLE
Invalid L1i size: 96KB on AMD A6 CPU

### ISSUE THREAD

**Issue by Ex0dium** [Dr-Noob/cpufetch#39] opened 2021-03-06 16:29 UTC
When I type either `cpufetch` or `cpufetch --debug` the program segfaults with the same message
```[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
zsh: segmentation fault (core dumped)  cpufetch --debug
```

Here is the output of `inxi -Fxz` concerning system info and cpu
```System:    Kernel: 5.11.2-arch1-1 x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: sway 1.5.1 Distro: ArcoLinux
           base: Arch Linux
Machine:   Type: Laptop System: LENOVO product: 81N3 v: Lenovo IdeaPad S145-15AST serial: <filter>
           Mobo: LENOVO model: LNVNB161216 v: SDK0R32866WIN serial: <filter> UEFI: LENOVO v: AYCN18WW date: 06/05/2019
CPU:       Info: Dual Core model: AMD A6-9225 RADEON R4 5 COMPUTE CORES 2C+3G bits: 64 type: MCP arch: Excavator rev: 0
           L2 cache: 1024 KiB
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 10384
           Speed: 2595 MHz min/max: 1300/2600 MHz boost: enabled Core speeds (MHz): 1: 2595 2: 2595
```

**Comment by Dr-Noob** [comment] 2021-03-06 21:23
Hi,

Thanks for your report. I wrote code some time ago to check that cache sizes were "reasonable". My idea was to find bugs in the cache read source code. 

96KB for L1 does not seem correct. I just searched a bit on the internet, and didn't found too much information about the L1 of your CPU, but maybe cpufetch is working properly, and the cache size is 96KB... Anyway, cpufetch should not crash, that was my bad!

I just pushed a commit to bugfix branch. Please, compile and run this fix (remember to do `git checkout bugfix` to checkout to the bugfix branch). cpufetch will not crash (I hope), but will print a message for unexpected cache sizes. Moreover, you will be able to view all the cache sizes. Because I need to know if cpufetch is buggy or your CPU actually has 96KB of L1, I need you to run `lscpu -C` too.

Summarizing, please:
- Checkout to bugfix branch, build and run cpufetch and paste the full output here (no `--debug` flag)
- Paste the output of `lscpu -C`

Thanks!

**Comment by Ex0dium** [comment] 2021-03-12 22:10
Hello, sorry for answering late
I cloned again the repo and compiled on the bugfix branch and now I get this output message
```[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues





                                                              Name:              AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G
                                                              Microarchitecture: Excavator
                                                              Technology:        28nm
                                                              Max Frequency:     2.60GHz
                                                              Cores:             1 cores (2 threads)
                                                              AVX:               AVX,AVX2
                                                              FMA:               FMA3,FMA4
                                                              L1i Size:          96KB
                                                              L1d Size:          32KB (64KB Total)
                                                              L2 Size:           1MB
                                                              Peak Performance:  41.60 GFLOP/s
```
  (the amd logo is not copied here but it shows up)
However it isn't the same cache size as `lscpu -C` says:
```
NAME ONE-SIZE ALL-SIZE WAYS TYPE        LEVEL SETS PHY-LINE COHERENCY-SIZE
L1d       32K      64K   16 Data            1   32        1             64
L1i       64K     128K 1024 Instruction     1    1        1             64
L2         1M       2M   16 Unified         2 1024        1             64

```

**Comment by Dr-Noob** [comment] 2021-03-13 21:42
Quite interesting...cpufetch and lscpu do not agree on the cache sizes and organization. This is not the first time I see this issue on AMD processors (see issue #28). As you can see in https://www.cpu-world.com/cgi-bin/CPUID.pl?CPUID=69501, it looks like cpufetch is right. Pretty strange to see a 96KB cache, though. For now, I will consider that cpufetch is right and lscpu is wrong (as I did with the previous AMD).

However, I can see another issue to solve in cpufetch. It says that your CPU has 1 core (which is clearly wrong). I would need additional information to try to track this issue. Would you mind running:

- `cpufetch --verbose`
- `cpufetch --debug`

in your CPU? Thank you very much for your help!

**Comment by Ex0dium** [comment] 2021-03-13 22:53
`cpufetch --verbose` gives this additional line:
```
[WARNING]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x0000000D). Using udev
```
and `cpufetch --debug` returns
```
[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.95 (x86_64 build)
AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G
- Max standard level: 0x0000000D
- Max extended level: 0x8000001E
- CPUID dump: 0x00670F00
```

Thanks!

**Comment by Dr-Noob** [comment] 2021-03-16 18:49
I'm sorry but I can't understand what is happening with the information provided by `--debug` and `--verbose`...

I've pushed a new commit to bugfix. I introduced the `--raw` option which provides an even greater level of debugging. Actually, it is the deepest debug level possible. 

Would you mind running `cpufetch --raw`? I hope this will be enough to finally understand what is going on! The output will be a bit large, you can directly paste it here or upload it somewhere like pastebin.

Sorry for the mess and thank you for your support.

**Comment by Ex0dium** [comment] 2021-03-27 19:25
Here's the output of `cpufetch --raw`:
https://haste.breizh.pm/raw/cewazaxesu

It looks like both core are detected although the program ends up interpreting them as threads :thinking:... I hope it will help you to solve this issue...

**Comment by Dr-Noob** [comment] 2021-03-30 08:52
Alright, that was a hard bug to find...

I think we got it. I found that some AMD processors don't provide information about the number of caches and if the CPU has more than one thread per core. It looks like your CPU is inside this set of CPUs, and cpufetch was just fetching invalid data.

Please, try the last commit I just pushed to bugfix and paste the output of:
- `cpufetch --debug`
- `cpufetch --verbose`

I hope to see some warnings, but cpufetch should report 2 cores and the chaches like that:

```
L1i Size: 96KB (192KB Total)
L1d Size: 32KB (64KB Total)
L2 Size: 1MB
```

I have no idea if those cache sizes are right or not. At least for now, I will consider them right until I find a clue that suggest they are not.

**Comment by brunomiguel** [comment] 2021-04-03 22:32
I have the exact same issue with an AMD A9-9420, even with the latest commit.

**Comment by Ex0dium** [comment] 2021-04-04 14:34
Here's the output for `cpufetch --debug` :
```[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.95 (x86_64 build)
AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G
- Max standard level: 0x0000000D
- Max extended level: 0x8000001E
- AMD topology extensions: 0
- CPUID dump: 0x00670F00
```
And here's the output for `cpufetch --verbose`
```[WARNING]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x0000000D). Using udev
[WARNING]: Can't read cache information from cpuid (needed extended level is 0x8000001D, max is 0x8000001E and topology_extensions=false)
[WARNING]: Fallback to old method using 0x80000005 and 0x80000006
[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
[WARNING]: Can't read topology information from cpuid (needed extended level is 0x8000001E, max is 0x8000001E and topology_extensions=false)
[WARNING]: Can't read topology information from cpuid (needed extended level is 0x8000001D, max is 0x8000001E and topology_extensions=false). Guessing cache topology





                                                              Name:              AMD A6-9225 RADEON R4, 5 COMPUTE CORES 2C+3G
                                                              Microarchitecture: Excavator
                                                              Technology:        28nm
                                                              Max Frequency:     2.60GHz
                                                              Cores:             2 cores
                                                              AVX:               AVX,AVX2
                                                              FMA:               FMA3,FMA4
                                                              L1i Size:          96KB (192KB Total)
                                                              L1d Size:          32KB (64KB Total)
                                                              L2 Size:           1MB
                                                              Peak Performance:  83.20 GFLOP/s
```

**Comment by Dr-Noob** [comment] 2021-04-06 10:39
@brunomiguel please, checkout to bugfix branch. cpufetch will work, but you will still see the message. Could you post the output of `cpufetch --debug` too (in the bugfix branch)? Thanks!

**Comment by Dr-Noob** [comment] 2021-04-06 10:43
**IMPORTANT!**

With the latest commit in bugfix branch, cpufetch now works well, but I am still unsure if the cache sizes are correct or not, since lscpu reported different values.

I will look in the Linux kernel code to understand what is going on, and will commit some patches if needed. Then, I will merge all the changes to master branch.

Thank you all for your reports!

**Comment by brunomiguel** [comment] 2021-04-06 11:43
> @brunomiguel please, checkout to bugfix branch. cpufetch will work, but you will still see the message. Could you post the output of `cpufetch --debug` too (in the bugfix branch)? Thanks!

Here is the output

[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.95 (x86_64 build)
AMD A9-9420 RADEON R5, 5 COMPUTE CORES 2C+3G 
- Max standard level: 0x0000000D
- Max extended level: 0x8000001E
- AMD topology extensions: 0
- CPUID dump: 0x00670F00

**Comment by alpvonkri** [comment] 2021-04-07 06:04
I can confirm that issue #45 seems solved in commit ec2ad4f

cpufetch --debug
[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.96 (x86_64 build)
AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G
- Max standard level: 0x0000000D
- Max extended level: 0x8000001E
- CPUID dump: 0x00660F01

**Comment by Dr-Noob** [comment] 2021-04-07 12:40
Sorry for the mess, but I need additional information. I need one of you to provide:

- The contents of the file `/sys/devices/system/cpu/cpu0/cache/index0/size` and `/sys/devices/system/cpu/cpu0/cache/index1/size`
- The output of `cpufetch --raw` again, because I've just uploaded a new commit (important: remember to update!)
- The output of `lscpu -C` (not neccesary in the case of Ex0dium)

Thank you guys!

**Comment by Ex0dium** [comment] 2021-04-07 19:35
- Here is the output for `cpufetch --raw` https://haste.breizh.pm/zaladohage.sql
- `/sys/devices/system/cpu/cpu0/cache/index0/size` contains `32K` and `/sys/devices/system/cpu/cpu0/cache/index1/size` contains `64K`

**Comment by alpvonkri** [comment] 2021-04-07 21:02
AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G

/sys/devices/system/cpu/cpu0/cache/index0/size = 32K
/sys/devices/system/cpu/cpu0/cache/index1/size = 96K
/sys/devices/system/cpu/cpu0/cache/index2/size = 1024K

I attach output files, as options cpufetch--raw is not working for me in latest main update (tell me if I need to do something in particular for this), and lscpu -C is also not working for me.

[cpufetch.debug.txt](https://github.com/Dr-Noob/cpufetch/files/6274474/cpufetch.debug.txt)
[cpufetch.raw.txt](https://github.com/Dr-Noob/cpufetch/files/6274476/cpufetch.raw.txt)
[lscpu.a.txt](https://github.com/Dr-Noob/cpufetch/files/6274477/lscpu.a.txt)
[lscpu.C.txt](https://github.com/Dr-Noob/cpufetch/files/6274478/lscpu.C.txt)
[lscpu.txt](https://github.com/Dr-Noob/cpufetch/files/6274479/lscpu.txt)

**Comment by gamerhat18** [comment] 2021-04-08 09:20
> AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G
> 
> /sys/devices/system/cpu/cpu0/cache/index0/size = 32K
> /sys/devices/system/cpu/cpu0/cache/index1/size = 96K
> /sys/devices/system/cpu/cpu0/cache/index2/size = 1024K
> 
> I attach output files, as options cpufetch--raw is not working for me in latest main update (tell me if I need to do something in particular for this), and lscpu -C is also not working for me.
> 
> [cpufetch.debug.txt](https://github.com/Dr-Noob/cpufetch/files/6274474/cpufetch.debug.txt)
> [cpufetch.raw.txt](https://github.com/Dr-Noob/cpufetch/files/6274476/cpufetch.raw.txt)
> [lscpu.a.txt](https://github.com/Dr-Noob/cpufetch/files/6274477/lscpu.a.txt)
> [lscpu.C.txt](https://github.com/Dr-Noob/cpufetch/files/6274478/lscpu.C.txt)
> [lscpu.txt](https://github.com/Dr-Noob/cpufetch/files/6274479/lscpu.txt)

I have the same APU, and so i have the same results. Also, `--raw` isnt working

**Comment by Dr-Noob** [comment] 2021-04-08 09:24
@gamerhat18 @alpvonkri To run `cpufetch --raw`, you need to checkout to the `bugfix` branch (`git checkout bugfix`), then build the project. If even with this instructions it is not working, please provide information about why is not working (the option is not being recognised, `cpufetch` segfaults...)

**Comment by gamerhat18** [comment] 2021-04-08 09:35
updated to bugfix, here's my `cpufetch --raw`

[raw.txt](https://github.com/Dr-Noob/cpufetch/files/6277632/raw.txt)

**Comment by Dr-Noob** [comment] 2021-04-08 11:19
Alright guys, I have researched around this issue and I think that I've come into a theory.

First, L1i size is 96KB. Confirmed. So `cpufetch` must not warn about the invalid size. I have come into this conclusion because cpuid always reports 96KB, so it's like the @Ex0dium `lscpu` must be wrong. In addition to that, I just found an official document from AMD (https://www.amd.com/system/files/TechDocs/55072_AMD_Family_15h_Models_70h-7Fh_BKDG.pdf) which confirms that the cache size is 96KB. I may question cpuid, lscpu or cpuworld, but not a official document from the manufacturer.

My theory is that the kernel version of @Ex0dium has a bug. I suspect that his kernel is quite old compared to the other guys here. Can you specify your kernel version @Ex0dium? And @gamerhat18 too, so we can compare both version. His kernel version must be greater than the Ex0dium's.

I have made a last commit to `bugfix`, removing the warning about the cache size. Please, give it a try. If we don't find any issues with that, I will close this issue afterwards.

**Comment by thegamerhat** [comment] 2021-04-09 06:22
Pop OS 20.04, Kernel 5.11 (updated this week earlier).

Also, I tried the latest commit of `bugfix` and here's the output. it doesnt show an error anymore.

![cpufetch](https://user-images.githubusercontent.com/38887390/114137549-fea70680-9929-11eb-949d-dbb9907228f2.png)

**Comment by Dr-Noob** [comment] 2021-04-09 06:49
Great, let's see what Ex0dium says. 

But your number of cores are reported wrongly, and I suspect this is the same issue as #57. I will upload a fix for it this morning, you should give it a try later.

**Comment by thegamerhat** [comment] 2021-04-09 07:58
I actually have 2 cores with SMT enabled, tho AMD says it's 4 cores for some reason.
Reading the contents of `/sys/devices/system/cpu/smt/active` tells me that SMT is enabled so i guess its just 2 cores, as it reflects in the performance.

![image](https://user-images.githubusercontent.com/38887390/114148410-54ce7680-9937-11eb-9f4f-6782a57212af.png)

**Comment by Ex0dium** [comment] 2021-04-09 09:22
Well, I'm on the 5.11.11-zen1-1-zen kernel so it's not an old one (I tested on 5.11.11-arch1 and I have the same bug)

**Comment by Dr-Noob** [comment] 2021-04-09 13:03
Ok guys, I think that it does not make much sense to keep talking about this, the issue it's solved now (although we don't know why Ex0dium's lscpu says that is 64KB...). I'm closing the issue and merging the changes to master.

@thegamerhat About the discussion on the number of cores/threads, you can join us in issue #57. It looks like your CPU has the same "issue", and I discovered another one at home. I honestly don't know what the hell is going on with that, but I will try to find it out

**Closed by Dr-Noob** 2021-04-09 13:03 UTC
