### ISSUE TITLE
"munmap_chunk(): invalid pointer" when executed on PowerPC 970

### ISSUE THREAD

**Issue by lukezenoob** [Dr-Noob/cpufetch#153] opened 2022-08-25 08:00 UTC
While this is a small project and I don't want to bother you with things like this, I am very eager to get this working on unusual hardware. Very happy you included PowerPC support.

The CPU in question is a dual-core, big endian, 64-bit PowerPC 970. It is running Gentoo Linux with GCC 11.3.

I receive the error `munmap_chunk(): invalid pointer` when running cpufetch. It compiles with no problem, i simply cannot execute it. `--debug` returns the same thing as well.

**Comment by Dr-Noob** [comment] 2022-09-05 06:13
Thanks for reporting the issue. Can you please follow [these guidelines](https://github.com/Dr-Noob/cpufetch/blob/master/CONTRIBUTING.md#22-i-found-a-bug-in-cpufetch-the-program-crashes--does-not-work-properly) and provide the information required so I can understand where the issue is?

Thanks!

**Comment by lukezenoob** [comment] 2022-10-05 03:25
Hi, sorry, i've provided as much info as possible. Neither of the options worked. Perhaps it is an endianness problem?

**Comment by Dr-Noob** [comment] 2022-10-05 06:08
Running valgrind should give some output. Did you try what's under "Stacktrace option 1 (best)" in the [guidelines](https://github.com/Dr-Noob/cpufetch/blob/master/CONTRIBUTING.md#22-i-found-a-bug-in-cpufetch-the-program-crashes--does-not-work-properly)? "Stacktrace option 2" would also be helpful. 

Without further information is impossible to fix the issue, since I don't know what is causing the failure.

**Comment by Dr-Noob** [comment] 2023-05-06 08:39
I have applied several patches and merged them into master branch. Can you try again to check if cpufetch works now?

**Comment by lukezenoob** [comment] 2023-05-15 23:49
I picked up an iMac G5 and version 1.04 is working on it! Not 1.02, which is the Gentoo ebuild i got it from.
![Screen Shot 2023-05-15 at 7 48 37 PM](https://github.com/Dr-Noob/cpufetch/assets/53693709/f0260a50-bb7d-41ce-b3bc-55e56fe1465d)

**Comment by Dr-Noob** [comment] 2023-05-16 07:37
Awesome! 

It's expected to work under 1.04 but not under 1.02 since the bug was fixed in 1.04 (it confirms that the issue was the same as the one reported in #178). Closing now.

**Closed by Dr-Noob** 2023-05-16 07:37 UTC
Labels: bug
